In [1]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [23]:
train_df = pd.read_csv('/content/drive/MyDrive/통계청공모전/1. 실습용자료.txt', sep = '|', encoding = 'cp949')
test_df = pd.read_csv('/content/drive/MyDrive/통계청공모전/2. 모델개발용자료.txt', sep = '|', encoding = 'cp949')

In [ ]:
e10 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/E10_digit1.csv')
roe10 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로버타digit1.csv')
re10 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Reduction_E10_digit1.csv')

In [ ]:
ko2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/E10_digit2.csv')
ro2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/RoBERTa_digit_2.csv')

In [24]:
ko2n = np.load('/content/drive/MyDrive/통계청공모전/E10_digit2.npy')
ro2n = np.load('/content/drive/MyDrive/통계청공모전/Roberta_digit_2.npy')

In [5]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

y_true = np.array(ko2.digit_2)
y_pred = np.array(ro2.digit_2)

print(classification_report(y_true, y_pred))

NameError: ignored

In [ ]:
temp = train_df.digit_1.value_counts()[train_df.digit_1.value_counts() < 10000].index.to_list()
n1 = train_df.query('digit_1 == @temp').digit_1.unique().tolist()
nn = roe10.reset_index().rename(columns = {'index':'number'}).query('digit_1 == @n1').number.values
nn

array([   63,   131,   148, ..., 99885, 99901, 99928])

In [ ]:
a = roe10.reset_index().rename(columns ={'index':'number'}).query('number == @nn.tolist()')

In [ ]:
b = re10.reset_index().rename(columns = {'index':'number'}).query('number != @nn.tolist()')

In [ ]:
pd.concat([a, b],axis = 0).sort_values(by=['number'], ascending = True).drop(['number','text'],axis = 1)

AI_id digit_1  digit_2  digit_3  text_obj   text_mthd text_deal
0      id_000001       I      NaN      NaN   치킨전문점에서    고객의주문에의해      치킨판매
1      id_000002       G      NaN      NaN      산업공구   다른 소매업자에게    철물 수공구
2      id_000003       S      NaN      NaN       절에서    신도을 대상으로    불교단체운영
3      id_000004       S      NaN      NaN     영업장에서       고객요구로     자동차튜닝
4      id_000005       I      NaN      NaN  실내포장마차에서   접객시설을 갖추고   소주,맥주제공
...          ...     ...      ...      ...       ...         ...       ...
99995  id_099996       G      NaN      NaN     사업장에서     일반인대상으로      버섯농장
99996  id_099997       Q      NaN      NaN     한의원에서     외래환자위주고        치료
99997  id_099998       G      NaN      NaN    일반점포에서       소비자에게      그림판매
99998  id_099999       R      NaN      NaN     사업장에서  일반인.학생대상으로    학습공간제공
99999  id_100000       L      NaN      NaN     사업장에서    대리현대아파트를        관리

[100000 rows x 7 columns]

In [28]:
en2 = (ko2n + ro2n) / 2
e = np.argmax(en2, axis = 1)
print(e)

[44 36 71 ... 37 69 55]


In [15]:
e.shape

(100000,)

In [11]:
en2

array([[-1.31256725,  1.22941674,  0.53029643, ..., -0.78045581,
        -0.83532332,  0.18730538],
       [-0.80825422,  0.15079548, -2.88227469, ..., -1.15770349,
        -1.42827443, -0.8521273 ],
       [-0.12240289,  0.12249395, -1.17086359, ...,  7.52604735,
        -1.00248757,  0.43730019],
       ...,
       [-0.94437888,  0.60777952, -1.86276164, ..., -1.08322896,
         0.07473992, -0.32922218],
       [-0.88379571, -0.25908902,  0.11771948, ...,  1.60452477,
        -0.57813893,  0.341256  ],
       [-0.50909809, -0.05847338, -2.12362801, ...,  0.9864842 ,
        -0.34677551,  0.92046341]])

In [7]:
np.array_equiv(np.argmax(ko2n, axis = 1), np.argmax(ro2n, axis = 1))

False

In [8]:
np.argmax(ko2n, axis = 1)
ko2

NameError: ignored

In [10]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column     Non-Null Count    Dtype 
---  ------     --------------    ----- 
 0   AI_id      1000000 non-null  object
 1   digit_1    1000000 non-null  object
 2   digit_2    1000000 non-null  int64 
 3   digit_3    1000000 non-null  int64 
 4   text_obj   983323 non-null   object
 5   text_mthd  956381 non-null   object
 6   text_deal  932348 non-null   object
dtypes: int64(2), object(5)
memory usage: 53.4+ MB


In [26]:
train_df['digit_2'] = train_df['digit_2'].astype(str)

In [27]:
from sklearn.preprocessing import LabelEncoder
e = np.argmax(en2, axis = 1)
print(e)
le = LabelEncoder()
train_df['digit_2'] = le.fit_transform(train_df['digit_2'])
print(le.inverse_transform(e.tolist()))

[44 36 71 ... 37 69 55]
['56' '46' '94' ... '47' '90' '68']


In [ ]:
ko2

Unnamed: 0      AI_id  digit_1  digit_2  digit_3  text_obj   text_mthd  \
0               0  id_000001      NaN       56      NaN   치킨전문점에서    고객의주문에의해   
1               1  id_000002      NaN       46      NaN      산업공구   다른 소매업자에게   
2               2  id_000003      NaN       94      NaN       절에서    신도을 대상으로   
3               3  id_000004      NaN       30      NaN     영업장에서       고객요구로   
4               4  id_000005      NaN       56      NaN  실내포장마차에서   접객시설을 갖추고   
...           ...        ...      ...      ...      ...       ...         ...   
99995       99995  id_099996      NaN       47      NaN     사업장에서     일반인대상으로   
99996       99996  id_099997      NaN       86      NaN     한의원에서     외래환자위주고   
99997       99997  id_099998      NaN       47      NaN    일반점포에서       소비자에게   
99998       99998  id_099999      NaN       90      NaN     사업장에서  일반인.학생대상으로   
99999       99999  id_100000      NaN       68      NaN     사업장에서    대리현대아파트를   

      text_deal                        text  
0          치킨판매       치킨전문점에서 고객의주문에의해 치킨판매  
1        철물 수공구       산업공구 다른 소매업자에게 철물 수공구  
2        불교단체운영         절에서 신도을 대상으로 불교단체운영  
3         자동차튜닝           영업장에서 고객요구로 자동차튜닝  
4       소주,맥주제공  실내포장마차에서 접객시설을 갖추고 소주 맥주제공  
...         ...                         ...  
99995      버섯농장          사업장에서 일반인대상으로 버섯농장  
99996        치료            한의원에서 외래환자위주고 치료  
99997      그림판매           일반점포에서 소비자에게 그림판매  
99998    학습공간제공     사업장에서 일반인 학생대상으로 학습공간제공  
99999        관리           사업장에서 대리현대아파트를 관리  

[100000 rows x 9 columns]